run:
  tests: false

# `golangci-lint linters` or See: https://golangci-lint.run/usage/linters/
linters:
  enable:
    # Auto Fixable linters (`golangci-lint linters | grep "auto-fix: true"`)
    - gofmt
    - goimports
    - misspell
    - whitespace
    - gci
    - godot
    - gofumpt
